/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BannerInfo: typeof import('./components/BannerInfo.vue')['default']
    BaseButton: typeof import('./components/core/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/core/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/core/BaseInput.vue')['default']
    BaseSearchSelect: typeof import('./components/core/BaseSearchSelect.vue')['default']
    BaseSelect: typeof import('./components/core/BaseSelect.vue')['default']
    CodeInput: typeof import('./components/core/CodeInput.vue')['default']
    copy: typeof import('./components/PopupOrder copy.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    LoadFile: typeof import('./components/LoadFile.vue')['default']
    Order: typeof import('./components/Order.vue')['default']
    PopupOrder: typeof import('./components/PopupOrder.vue')['default']
    PopupRef: typeof import('./components/PopupRef.vue')['default']
    PopupSupport: typeof import('./components/PopupSupport.vue')['default']
    PopupTariff: typeof import('./components/PopupTariff.vue')['default']
    RefItem: typeof import('./components/RefItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBody: typeof import('./components/core/TabBody.vue')['default']
    TabContent: typeof import('./components/core/TabContent.vue')['default']
    TabItem: typeof import('./components/core/TabItem.vue')['default']
    TabItemList: typeof import('./components/core/TabItemList.vue')['default']
    Tariff: typeof import('./components/Tariff.vue')['default']
  }
}
